In [2]:
import torch
import torchvision

In [71]:
class_num = 3
y_pred = torch.tensor([[0,1,0],
              [1,0,0],
              [0,0.2,0.8]])
y_true = torch.tensor([[0,1,0],
                       [1,0,0],
                       [0,1,0]])
class_pred = y_pred.max(1).indices
class_true = y_true.max(1).indices
mask = ((class_true != class_pred)[:,None] * 1).mm(torch.ones((1,class_num)))
y_pred_filtered = y_pred[mask == 1].view(-1,class_num)
y_true_filtered = y_true[mask == 1].view(-1,class_num)

RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #3 'mat2' in call to _th_addmm_out

In [72]:
y_pred_filtered

tensor([[0.0000, 0.2000, 0.8000]])

In [73]:
y_true_filtered

tensor([[0, 1, 0]])

In [74]:
import functools
l1 = torch.tensor([[1,0,0],[0,0,1],[1,0,0]])
l2 = torch.tensor([[1,0,0],[0,0,1],[1,0,0]])
l3 = torch.tensor([[1,0,0],[0,0,1],[1,0,0]])
torch.cat((l1,l2,l3),1)


tensor([[1, 0, 0, 1, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 1, 0, 0, 1],
        [1, 0, 0, 1, 0, 0, 1, 0, 0]])

In [66]:
class CourtNet(torch.nn.Module):
    def __init__(self, jurors, class_num):
        super(CourtNet, self).__init__()
        self.jurors = jurors
        self.class_num = class_num
        l1_output_size = class_num * len(jurors) // 2
        self.l1 = torch.nn.Linear(class_num * len(jurors), l1_output_size)
        self.f1 = torch.nn.functional.relu
        self.l2 = torch.nn.Linear(l1_output_size, class_num)
        def f2(input_tensor):
            return torch.nn.functional.softmax(input_tensor, 1)
        self.f2 = f2

    def forward(self, x):
        jurors_pred = torch.cat([juror(x) for juror in self.jurors], 1)
        return self.f2(self.l2(self.f1(self.l1(jurors_pred))))


In [70]:

optimizer = torch.optim.Adam(net.parameters())

for (i,(x,y_true)) in dataloader:
    y_pred = net(x)
    class_pred = y_pred.max(1).indices
    class_true = y_true.max(1).indices
    mask = ((class_true != class_pred)[:,None] * 1).mm(torch.ones((1,class_num)))
    y_pred_filtered = y_pred[mask == 1].view(-1,class_num)
    y_true_filtered = y_true[mask == 1].view(-1,class_num)





tensor([[0.6769, 0.1620, 0.1611],
        [0.7196, 0.1497, 0.1307],
        [0.6750, 0.1780, 0.1470]], grad_fn=<SoftmaxBackward>)

tensor([[ 1.2117,  2.0085, -0.6506, -1.1995]], grad_fn=<AddmmBackward>)